// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvByxHE4aS_Q9DyQhD8AFSoZ55fx_OYMw',
    appId: '1:661823581081:web:a35cb1d4dac593a2d18108',
    messagingSenderId: '661823581081',
    projectId: 'myfirebase-83e20',
    authDomain: 'myfirebase-83e20.firebaseapp.com',
    storageBucket: 'myfirebase-83e20.appspot.com',
    measurementId: 'G-222Y8ZWVLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyUNc57NMGgQjvVXeYi727Ri4pVuSaiQ',
    appId: '1:661823581081:android:847c8e382d085431d18108',
    messagingSenderId: '661823581081',
    projectId: 'myfirebase-83e20',
    storageBucket: 'myfirebase-83e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB7EQlJlChwp4HEwClcn_wLX9XdgzI8_U',
    appId: '1:661823581081:ios:e90335afc2c83b20d18108',
    messagingSenderId: '661823581081',
    projectId: 'myfirebase-83e20',
    storageBucket: 'myfirebase-83e20.appspot.com',
    iosClientId: '661823581081-fqjb1ok6m997pmguvvj013o495il05lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashion',
  );
}
